### ISSUE TITLE
Drop NS API incompatible implementations (SS2)?

### ISSUE THREAD

**Issue by spiliot** [ProductEarthSolutions/netsumo#13]
PR https://github.com/3EN-Cloud/netsumo/pull/11 attempts to make `getValue()`/`getText()` API compatible, which raises the question if there's a need to keep the incompatible implementation (as the PR does)?

One reason to keep would be for simplicity when trying to access a value in the test (instead of passing verbose objects the API requests). I propose if there's indeed such need, to add special functions (i.e. `_valueOfField('fieldName')`) so we leave functions with only a concrete, public API compatible implementation.

To maintain backwards compatibility with existing tests, removing the incompatible implementation is better done with the next major version bump.

**Comment by benpf-pes** [comment]
Both `getValue('fieldId')` &` getValue({ fieldId: 'fieldId' })` are both API compatible, so no reason not to have both IMO. I understand the concern though and thanks for flagging this. It's create to see the up take in Netsumo 👍
