### ISSUE TITLE
Support SCA nlobjRequest, nlobjResponse and SC.Model Mocking

### ISSUE THREAD

**Issue by sazr** [ProductEarthSolutions/netsumo#2]
Will NetSumo support more NetSuite API objects in the future? For example; `nlobjRequest`, `nlobjResponse` and `SC.Model`? These are used alot in SuiteCommerce Advanced. http://suitecoder.appspot.com/static/api.html

I'm currently at the stage of testing my SCA Services (`Foo.Service.ss` files) and SCA Models (`Foo.Model.js` files). I need to pass a mock `nlobjRequest` to my service to test it and somehow get a mock `nlobjResponse`. 

If there are no immediate plans to expand the library with these objects any advice on how I can create them to contribute to this repo? :)

**Comment by matthewwilson** [comment]
Thanks @sazr. Adding these objects is something that we want to do but not sure when we will be implementing them. 

Implementing nlobjRequest and nlobjResponse should be similar to how we have implemented nlobjRecord. 

As for SC.Model, it will require a bit more thought, SCA uses require.js to handle the loading of modules and we could maybe leverage that within this project as well, or use the node.js module loader.

So for example `var GearStory = require('GearStory.Model');` will just load in your GearStory model, and any nlapi functions used within it will already be mocked by NetSumo. 

I can try and tackle SC.Model if you want to have a go at implementing nlobjRequest and response!

**Comment by sazr** [comment]
Sounds good :D 

I will attempt to tackle the `nlobjRequest`, `nlobjResponse` although I'll probably need advice as I go. I'll look at the other mock objects as a template. Having a `SC.Model` would be incredibly useful for SCA developers.
