### ISSUE TITLE
Test runner

### ISSUE THREAD

**Issue by sirishasriramineni207** [ProductEarthSolutions/netsumo#8]
Hi, how can we run the tests. where can we get this app. Please give me the complete info about this. can we run this in our local systems. We want to unit test  NetSuite 2.0 scripts.

**Comment by saeedanabtawi** [comment]
Same problem here @matthewcodes

**Comment by matthewwilson** [comment]
Hi @sirishasriramineni207 & @saeedanabtawi we used jest as our test runner - https://jestjs.io/

**Comment by saeedanabtawi** [comment]
Thanks
